import Head from 'next/head'
import Script from 'next/script'
import styles from '@/styles/Home.module.css'
import Viewer from '../components/viewer'

export default function Home() {

  return (
    <>
      <Head>
        <title>APS Next.js Viewer Sample</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1, user-scalable=no" />
        <meta charSet="utf-8" />
      </Head>
      <Script src="https://developer.api.autodesk.com/modelderivative/v2/viewers/7.*/viewer3D.js" strategy="beforeInteractive" />
      <Viewer/>
    </>
  )
}
